from .animal import Animal
from .bear import Bear
from .dolphin import Dolphin
from .fish import Fish
from .gorilla import Gorilla
from .horse import Horse
from .lizard import Lizard
from .llama import Llama
from .monkey import Monkey
from .seahorse import Seahorse
from .shark import Shark
from .skink import Skink
from .snake import Snake
from .tiger import Tiger
from .turtle import Turtle
from .whale import Whale
